### PR TITLE
Add PHP 7.3 support

### PR DESCRIPTION
**Pull request by eXorus**

### CODE REVIEW

**Comment by stevenscg** [comment]
I hit the same issue that the Travis run above did.

It looks like Remi may have (or be gaining) the ability to push to pecl for this.

See:
https://github.com/php/pecl-mail-mailparse/pull/5
https://externals.io/message/102685

My setup today was:
php 7.3.1
mailparse 3.0.2 (from pecl)
Alpine 3.8 and CentOS 7.6

**Comment by eXorus** [comment]
I'm waiting like you the release.

I think you can build your own package of mailparse from the source.

**Comment by stevenscg** [comment]
Thanks @eXorus and thanks for your work on this project (that probably doesn't get said enough in OSS)!

I'm watching the mailparse thread as well. If we get to a point where we really need to move up, we'll build it locally.

**Comment by stevenscg** [comment]
Nice work @eXorus! Thanks for driving this through.

**Pull request merged**
