### PR TITLE
Implemented getMimePartStr() for attachments

### PR DESCRIPTION
**Pull request by HadyHallak**
Added ability for getting string mime part of an attachment object.

### CODE REVIEW

**Comment by eXorus** [comment]
Sorry too many errors, could you check your code and explain why you need this ?

Thanks for your contribution.

**Comment by HadyHallak** [comment]
This introduces a method for getting the mime body of an attachment. I've used this in a mail rewriting task, where I had to add a disclaimer for outgoing emails on the fly.

**Comment by eXorus** [comment]
Thanks, could you add two tests to test getMimePartStr() from data and stream ?

And maybe add a line to readme to explain the usage.

**Comment by eXorus** [comment]
Great job sorry for the delay.
I always don't understand the usage :) so you retrieve incoming email and for each attachments you build another email and change the body of the attachment

Like I send you an email with txt file where we have inside "hello boy !"

And with another library you send another email with the attachment "Be careful, hello boy!"

Is it this ?
so why you don't use getAttachments, modify the attachment, and send it back ?

**Comment by HadyHallak** [comment]
I'm not editing the attachments, but just getting the "MIME Part" for each one.

Like a txt file attachment with the contents "hello boy !", this function does not return "hello boy !" but it returns a full mime part of it as follows:

```
Content-Type: ...
Content-Disposition: ...
...

TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY ..... {base_64_file_contents}
```

I've used this to iterate through the attachments of incoming messages, and write them out again with an altered email body.

**Pull request merged**
