### PR TITLE
A bunch of stuff for Travis CI

### PR DESCRIPTION
**Pull request by duncan3dc**
* Use `composer update` to test against the highest dependencies
* Also test against the lowest supported dependencies
* Added testing on the upcoming php release (7.0) (with allowed failure for now)
* Use [container-based](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) travis builds 
* Follow community standards for phpunit tests (filenames, bootstrap, etc)

Doing this uncovered an issue in the dependencies. PHPUnit has a bug that was fixed but isn't included until the unreleased 4.5 version. Adding a requirement for `phpunit/php-token-stream` of at least version `1.3.0` replicates the [upstream fix](https://github.com/sebastianbergmann/phpunit/pull/1631)

### CODE REVIEW

**Comment by duncan3dc** [comment]
It looks like GitHub didn't pick up this merge because it was squashed

**Comment by eXorus** [comment]
Maybe I'm doing a wrong way to merge it. It was not possible to auto-merge with Github so I try manually.

I will work again tomorrow to publish the new version.
Thanks for your contribution.

**Comment by duncan3dc** [comment]
No problem, I'd hold off on publishing yet though, I think we could get some new features in ready for a 2.0 release.

I'm currently looking into a pure php version of mailparse, then we can remove the dependency on the unmaintained pecl package

**Comment by clementhk** [comment]
Looks a lot more proper than before @duncan3dc, awesome.

**Pull request closed without merging**
