### PR TITLE
Check before attempting to perform a zero-length fread

### PR DESCRIPTION
**Pull request by matcho**
Avoids a Warning thrown by fread() in case of zero-length message body

### CODE REVIEW

**Comment by eXorus** [comment]
Thanks for your contribution to improve the quality.

Do you have a test file where start > end to add it to the project ?

Also I prefer to write 
```php
if ($end-$start>0) return '';

fseek($this->stream, $start, SEEK_SET);
return fread($this->stream, $end-$start);
```

What do you think ?

**Comment by matcho** [comment]
I prefer your way too, just didn't want to be shout at because of introducing multiple returns, that tend to irritate a lot of people ^^
Pull request updated.
Attached, an email (disguised headers) with a zero-length body content, that comes from a mailing list. Until now I've never been confronted to a body length < 0.

Salut depuis Montpellier !
[zero-length-body-email-example.txt](https://github.com/php-mime-mail-parser/php-mime-mail-parser/files/57928/zero-length-body-email-example.txt)

**Comment by matcho** [comment]
lol, the auto reviewer shouts at us now ^^

**Comment by matcho** [comment]
Mhh... and now coverage decreases because of multiple returns, I guess. What do you think ? Do I revert back to the first version ? Ultimately, it seems to be the most politically correct way, regarding coverage requirements.

**Comment by eXorus** [comment]
No we need to add the test file to the test and check that body return '' in the case of zero-length body content

**Comment by matcho** [comment]
Mh, I don't understand why Travis CI build failed (I'm pretty new to all those tools). Anyway all the tests work on my copy, so my skills stop here, I lend this over to you.

Cheers

**Comment by eXorus** [comment]
Thanks I will try to merge soon.

**Comment by CSG7** [comment]
Sorry for putting pressure to this, but I think this is a critical error which should be fixed soon.

**Comment by eXorus** [comment]
Thanks to pressure me, I totaly forgot it.
Now it's published in 2.2.1

**Pull request merged**
