### PR TITLE
Parser::getRawHeader() may returns array

### PR DESCRIPTION
**Pull request by anton-bel**
getRawHeader may return array, if the mail has multiple header lines, like a Received

### CODE REVIEW

**Comment by eXorus** [comment]
Thanks, could you add a test?

**Comment by bendavies** [comment]
came looking for this as well.
getHeader('received') returns the first received header when there can often be many.
would be nice if there was a method to return an array here of all of the `received` headers, like https://github.com/laminas/laminas-mail/blob/2.24.x/src/Storage/Part.php#L341

**Comment by eXorus** [comment]
Hello,

I tested it, but I couldn't reproduce the issue:
```php

        $parser = new Parser();
        $parser->setText(<<<MIME
        From: expéditeur@example.com
        To: destinataire@example.com
        Subject: Exemple d'e-mail MIME avec en-tête Received
        Received: from mail.example.com (mail.example.com [192.168.1.1])
            by mx.example.net (Postfix) with ESMTPS id ABC12345
            for <destinataire@example.com>; Mon, 20 Sep 2023 10:00:00 -0400 (EDT)
            (envelope-from expéditeur@example.com)
            (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
            (No client certificate requested)
            by mail.example.com (Postfix) with ESMTPSA id DEF67890
            for <destinataire@example.com>; Mon, 20 Sep 2023 09:59:59 -0400 (EDT)
            (envelope-from expéditeur@example.com)

        Content-Type: multipart/mixed; boundary="frontière123"

        --frontière123
        Content-Type: text/plain

        Bonjour,

        Ceci est un exemple d'e-mail MIME avec un en-tête "Received" comprenant plusieurs lignes.

        Cordialement,
        Expéditeur

        --frontière123
        Content-Type: application/pdf; name="document.pdf"
        Content-Disposition: attachment; filename="document.pdf"

        [Contenu du fichier PDF ici]

        --frontière123--
        MIME
        );
        $subject = $parser->getHeader('Subject');
        $this->assertEquals("Exemple d'e-mail MIME avec en-tête Received", $subject);

        $received = $parser->getHeader('Received');
        $this->assertEquals("from mail.example.com (mail.example.com [192.168.1.1])    by mx.example.net (Postfix) with ESMTPS id ABC12345    for <destinataire@example.com>; Mon, 20 Sep 2023 10:00:00 -0400 (EDT)    (envelope-from expéditeur@example.com)    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))    (No client certificate requested)    by mail.example.com (Postfix) with ESMTPSA id DEF67890    for <destinataire@example.com>; Mon, 20 Sep 2023 09:59:59 -0400 (EDT)    (envelope-from expéditeur@example.com)", $received);
        $received_raw = $parser->getRawHeader('Received');
        $this->assertEquals("from mail.example.com (mail.example.com [192.168.1.1])    by mx.example.net (Postfix) with ESMTPS id ABC12345    for <destinataire@example.com>; Mon, 20 Sep 2023 10:00:00 -0400 (EDT)    (envelope-from expéditeur@example.com)    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))    (No client certificate requested)    by mail.example.com (Postfix) with ESMTPSA id DEF67890    for <destinataire@example.com>; Mon, 20 Sep 2023 09:59:59 -0400 (EDT)    (envelope-from expéditeur@example.com)", $received_raw);
        $headers = $parser->getHeaders();
        $this->assertEquals([
            'from' => 'expéditeur@example.com',
            'to' => 'destinataire@example.com',
            'subject' => "Exemple d'e-mail MIME avec en-tête Received",
            'received' => 'from mail.example.com (mail.example.com [192.168.1.1])    by mx.example.net (Postfix) with ESMTPS id ABC12345    for <destinataire@example.com>; Mon, 20 Sep 2023 10:00:00 -0400 (EDT)    (envelope-from expéditeur@example.com)    (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))    (No client certificate requested)    by mail.example.com (Postfix) with ESMTPSA id DEF67890    for <destinataire@example.com>; Mon, 20 Sep 2023 09:59:59 -0400 (EDT)    (envelope-from expéditeur@example.com)',
        ], $headers);
```

This test passed, which means that `getHeader('received')` or `getHeaders()['received']` doesn't return an array but rather a string with X lines separated by spaces.

**Comment by eXorus** [comment]
I was able to reproduce it with 2 headers, but it's an edge case that I'm not quite sure how to handle because in 99% of the cases, we just want to have a string and not an array.
```php

        $parser = new Parser();
        $parser->setText(<<<MIME
        From: expéditeur@example.com
        To: destinataire@example.com
        Subject: Exemple d'e-mail MIME avec en-tête Received
        Received: from first line
        Received: from second line

        Content-Type: text/plain

        hello world!
        MIME
        );
        $subject = $parser->getHeader('Subject');
        $this->assertEquals("Exemple d'e-mail MIME avec en-tête Received", $subject);

        $received = $parser->getHeader('Received');
        $this->assertEquals("from first line", $received);
        $received_raw = $parser->getRawHeader('Received');
        $this->assertEquals(["from first line", "from second line"], $received_raw);
        $headers = $parser->getHeaders();
        $this->assertEquals([
            'from' => 'expéditeur@example.com',
            'to' => 'destinataire@example.com',
            'subject' => "Exemple d'e-mail MIME avec en-tête Received",
            'received' => ["from first line", "from second line"],
        ], $headers);

```
I agree that it's not ideal because `getHeader` and `getHeaders` should return the same type, but introducing a breaking change is inevitable.

**Comment by fresent** [comment]
@eXorus I see the pull request is still open for this, can we please push this mainstream?
We are running into this exact thing.

**Comment by eXorus** [comment]
I added the test and it's merged.
Thank you for the reminder.

**Pull request merged**
