### PR TITLE
Ignore message body in getAttachments

### LINKED ISSUE #112: Text and html part as attachment
Why do you expect to get noname attachments for text and html part of [m0015](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8015cfb76b8bcd0c38c658231235863656dc43e8/tests/mails/m0015)?
[expected attachments](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/8015cfb76b8bcd0c38c658231235863656dc43e8/tests/ParserTest.php#L558-L578)

I would expect an empty array for `getAttachments()`..

### PR DESCRIPTION
**Pull request by gharlan**
fixes #112

### CODE REVIEW

**Comment by eXorus** [comment]
Any news @gharlan ?

**Comment by gharlan** [comment]
Sorry, I was on vacation.

Like this?

**Comment by fko2221** [comment]
+1 for this

**Comment by eXorus** [comment]
Nice work

**Pull request merged**
