### PR TITLE
Added option to include/exclude inline attachments

### PR DESCRIPTION
**Pull request by fko2221**
Added an optional argument to getAttachments and saveAttachments to include inline attachments (defaults to false). Also update the README file accordingly.

### CODE REVIEW

**Comment by fko2221** [comment]
I changed the default for `$include_inline` to true to prevent the unit tests from failing

**Comment by eXorus** [comment]
Thanks a lot it's a very good job.

But we are missing some test about include inline attachments to false

**Comment by fko2221** [comment]
Tell me what you think of the new unit test. It processes all the sample message again but with $include_inline set to false.

**Comment by eXorus** [comment]
It will be fine like this for the moment. Thanks.

I really need to work on a new version 3.0 with better improvement and better structure for test and parser.

**Pull request merged**
