### PR TITLE
Copy editing suggestions in README

### PR DESCRIPTION
**Pull request by eryno**
I meant to get to this sooner, but I hope it's still useful. Please review that everything I've written is correct, because I had to make some guesses about what you meant. Especially the "Why" section (which is the most important section to get right!).

### CODE REVIEW

**Comment by eXorus** [comment]
Thanks a lot.
One things seems to be wrong : Create and send webmail 

It's possible to create an webmail I do that but what do you mean by send ?

**Comment by eryno** [comment]
@noobiwan: Good catch, mistype on my part.

@eXorus: I was trying to reword "-If you need to parse and read email from server like postfix. You can also create a webmail and insert into your database emails with all information like subject, html body, attachments, ...", and I assumed that "create a webmail" meant "send email", but it looks like I was wrong.

Can you explain what you mean by "create a webmail"? I've only seen "webmail" used to describe a web interface for accessing POP3 or IMAP mails. I don't understand it in this context.

**Comment by noobiwan** [comment]
@eryno what @eXorus probably meant is that this library is just for reading/parsing email and not for sending. Yes you can send email in a webmail but you would need another component for that.

**Comment by eryno** [comment]
@lewiz: Ah, I think I follow now. Thanks for the clarification. I'll clean
that part up.

**Comment by eXorus** [comment]
Thanks @eryno and @noobiwan

**Pull request merged**
