### PR TITLE
Update Parser.php

### PR DESCRIPTION
**Pull request by Kuzuto**
Preg_replace on filename

### CODE REVIEW

**Comment by eXorus** [comment]
Hello,

Why do you need to do this ? could you explain it and maybe add a new test for that ?

**Comment by Kuzuto** [comment]
If the mail-header don't have a filename content, but only name content, the getAttachments is returning filename with .. or / 
I can post e-mail with e-mail header like this, and saveAttachments will save the file in a different dir

Content-Type: application/pdf;
 name="randomname/../../../../../../somefile.pdf"
Content-Transfer-Encoding: base64
Content-Description: 4509990669 / 333292

If I don't use RandomFile in my saveAttachment() I have a problem..

**Comment by eXorus** [comment]
Cool, could you add an test about this ?

**Comment by Kuzuto** [comment]
I will be right on it..

**Pull request closed without merging**
