### PR TITLE
Escape all potentially unsafe characters from attachements filenames.

### LINKED ISSUE #133: Error when saving attachments with slashes in the name (as a date)
Hi, 

the following error occurs when trying to save and read attachments with / in the name.

Error:

Command output: PHP Warning:  fopen(/var/spool/filter/attachments/A File with slashes in the name - 01/01/2017.pdf): failed to open stream: No such file or directory in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 473 PHP Fatal error:  Uncaught exception 'PhpMimeMailParser\Exception' with message 'Could not write attachments. Your directory may be unwritable by PHP.' in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php:480 Stack trace: #0 /opt/filter/script.php(118): PhpMimeMailParser\Parser->saveAttachments('/var/spool/filt...', Array) #1 {main}   thrown in /opt/filter/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php on line 480)

### PR DESCRIPTION
**Pull request by xqus**
Fixes #133

### CODE REVIEW

**Comment by eXorus** [comment]
Thanks for your contribution, could you add one test to test this behaviour ?

**Comment by xqus** [comment]
Added a testcase. The regular test for attachment filenames will make sure valid filenames are not changed. The new test will make sure invalid filenames are escaped.

**Comment by eXorus** [comment]
Thanks @xqus

**Comment by elbyvilayil** [comment]
@eXorus there is any way for get attachment contents as its is (without decode or convert to the original format )?

**Comment by eXorus** [comment]
@elbyvilayil Why do you ask this here ? do you talk about attachment filename or attachment contents ?

**Comment by elbyvilayil** [comment]
@eXorus attachment contents

**Pull request merged**
